BASE_MARKET = 'BTC'

UPDATE_MARKET_DB_EACH_X_MIN = 6 * 5 # minutes * 6 times 10 seconds

PERIOD = 10

BTC_INITIAL_BALANCE = 0.005
BTC_QUANTITY_TO_BUY = 0.0005

VOLUME_BOTTOM_THRESHOLD_OF_GROWTH = 0

BOTTOM_THRESHOLD_OF_GROWTH = 0

CEIL_THRESHOLD_OF_GROWTH = 1

THRESHOLD_OF_LOST = 10

THRESHOLD_OF_GAIN = 2

BID_MEAN_GROWTH = 3

PERIOD_GROWTH = 30

TREND_GROWTH = 0

BUY_ETH_MARKET = false

BUY_BITCNY_MARKET = false

BUY_USDT_MARKET = false

PERCENTILE_VOLUME = 66

PERCENTILE_ASK_BID = 66

SPREAD_LIMIT = 0.5