UPDATE_MARKET_DB_EACH_X_MIN = 10 * 6 # minutes * 6 times 10 seconds

BTC_INITIAL_BALANCE = 0.005
BTC_QUANTITY_TO_BUY = 0.0005

THRESHOLD_TO_SELL = 3

THRESHOLD_TO_BUY = 3

GAIN_FACTOR = 1

BUY_ETH_MARKET = false

BUY_BITCNY_MARKET = false

BUY_USDT_MARKET = false